<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>promise</title>
  </head>

  <body>
    <script>
      //then()方法成功
      //catch()方法失败
      //finally()方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。该方法是 ES2018 引入标准的。
      //all()方法用于将多个 Promise 实例，包装成一个新的 Promise 实例
      // p的状态由p1、 p2、 p3决定， 分成两种情况。
      // （ 1） 只有p1、 p2、 p3的状态都变成fulfilled， p的状态才会变成fulfilled， 此时p1、 p2、 p3的返回值组成一个数组， 传递给p的回调函数。
      // （ 2） 只要p1、 p2、 p3之中有一个被rejected， p的状态就变成rejected， 此时第一个被reject的实例的返回值， 会传递给p的回调函数。

      //Promise的执行顺序时 new Promise -> then()收集回调->resolve/reject 执行回调，这一顺序是建立在executor是
      //异步任务的前提上的，如果executor是一个同步任务，那么顺序就会变成new Promise->resolve/reject执行->then()收集
      //回调，resolve的执行跑到then之前去了，为了兼容这种情况，我们给resolve/reject执行回调操作包一个setTimeout，让它异步执行

      //这里插一句,有关这个setTimeout,其实还有一番学问。虽然规范没有要求回调应该被放进宏任务队列还是微任务队列，但其实
      // Promise的默认实现是放进了微任务队列，我们的实现(包括大多数Promise手动实现和polyfill的转化)都是使用setTimeout放入了宏任务队列
      // (当然我们也可以用MutationObserver模拟微任务)

      const PENDING = "pending";
      const FULFILLED = "fulfilled";
      const REJECTED = "rejected";
      class MyPromise {
        //构造方法接收一个回调
        constructor(executor) {
          console.log("第一步", "初始化Promise对象内部数据");
          this._state = PENDING; //Promise状态
          this._value = undefined; //储存then回调return的值
          this._resolveQueue = []; //then收集的执行成功的回调队列
          this._rejectQueue = []; //then收集的执行失败的回调队列
          //由于resolve/reject是在executor内部被调用,因此需要使用箭头函数固定this指向,否则找不到this._resolveQueue
          let _resolve = (val) => {
            //把resolve执行回调的操作封装成一个函数,放进setTimeout里,以兼容executor是同步代码的情况
            const run = () => {
              console.log(
                "第六步,then已经将收集的依赖添加到了resolveQueue/rejectQueue队列中了,执行宏任务中的_resolve释放"
              );
              // console.log("_state", this._state);
              if (this._state != PENDING) return;
              this._state = FULFILLED; //变更状态
              this._value = val; //存储当前value
              // console.log("_value>>>>>>>>>>>>xxxxxxxxxxx", this._value);
              //这里之所以使用一个队列来存储回调，是为了实现规范要求的“then”方法可以被同一个promise调用多次
              //如果使用一个变量而非队列来存储回调，那么即使多次p1.then()也只会执行一次回调
              // console.log("_resolveQueue", this._resolveQueue);
              while (this._resolveQueue.length) {
                const callback = this._resolveQueue.shift();
                // console.log("callback", callback);
                callback(val);
              }
            };
            console.log(
              "第三步",
              "执行封装好的_resolve/_reject函数,为了兼容executor是同步情况下放进setTimeout宏任务中等待then收集之后在执行"
            );
            setTimeout(run);
          };

          let _reject = (val) => {
            const run = () => {
              if (this._state != PENDING) return;
              this._state = REJECTED;
              this._value = val;
              while (this._rejectQueue.length) {
                const callback = this._rejectQueue.shift();
                callback(val);
              }
            };
            setTimeout(run);
          };
          // new Promise()时立即执行executor,并传入resolve和reject
          console.log(
            "第二步",
            "实例化Promise对象执行constructor构造函数,执行constructor传入的回调函数(resolve,reject)=>{}"
          );
          executor(_resolve, _reject);
        }
        //值穿透&状态已变更的情况
        //1，值穿透：根据规范，如果then()接收的参数不是function,那么我们应该忽略它。如果没有忽略
        // 当then()回调不为function时将会抛出异常，导致链式调用中断
        //2，处理状态为resolve/reject的情况：其实我们上边then()的写法时对应状态为padding的情况
        // 但是有些时候，resolve/reject在then()之前就被执行(比如Promise.resolve().then()),
        // 如果这个时候还把then()回调push进resolve/reject的执行队列里，那么回调将不会被执行，
        // 因此对于状态已经变为fulfilled或reject的情况，我们直接执行then回调：
        //then方法接收一个成功的回调和一个失败的回调，并push进对应队列
        then(resolveFn, rejectFn) {
          console.log("第四步", "then开始收集传入的逻辑");
          //根据规范，如果then的参数不是function，则我们需要忽略它，让链式调用继续往下执行
          typeof resolveFn !== "function"
            ? (resolveFn = (value) => value)
            : null;
          typeof rejectFn !== "function"
            ? (rejectFn = (reason) => {
                throw new Error(
                  reason instanceof Error ? reason.message : reason
                );
              })
            : null;
          //return一个新的promise
          return new MyPromise((resolve, reject) => {
            //把resolveFn重新包装一下，再push进resolve执行队列，这是为了能够获取回调的返回值进行分类讨论
            const fulfilledFn = (value) => {
              console.log("第七步,执行then收集到的依赖");
              try {
                //执行第一个(当前的)Promise的成功回调，并获取返回值
                const x = resolveFn(value);
                // console.log("x>>>", x);
                // console.log("resolve>>>", resolve);
                //分类讨论返回值，如果是promise，那么等待Promise状态变更，否则直接resolve
                //这里resolve之后，就能被下一个.then的回调获取到返回值，从而实现链式调用
                x instanceof MyPromise ? x.then(resolve, reject) : resolve(x);
              } catch (error) {
                reject(error);
              }
            };
            //reject 同理
            const rejectedFn = (value) => {
              try {
                const x = rejectFn(value);
                x instanceof MyPromise ? x.then(resolve, reject) : resolve(x);
              } catch (error) {
                reject(error);
              }
            };
            console.log(
              "第五步",
              "根据当前状态判断,如果是pending状态将对应的依赖添加到resolveQueue/rejectQueue的队列中,否则直接执行then收集的依赖"
            );
            // console.log("_state>>>", this._state);
            switch (this._state) {
              // 当状态为pending时，把then回调push进resolve/reject执行队列，等待执行
              case PENDING:
                this._resolveQueue.push(fulfilledFn);
                this._rejectQueue.push(rejectedFn);
                break;
              case FULFILLED:
                fulfilledFn(this._value);
                break;
              case REJECTED:
                rejectedFn(this._value);
                break;
            }
          });
        }
        // catch()方法返回一个Promise,并且处理拒绝的情况。它的行为与调用
        // Promise.prototype.then(undefined,onRejected)相同。
        // catch方法其实就是执行一下then的第二个回调
        catch(rejectFn) {
          return this.then(undefined, rejectFn);
        }
      }
      const p1 = new MyPromise((resolve, reject) => {
        resolve("同步executor测试~~~"); //同步executor测试
      });
      p1.then((res) => {
        console.log("第八步,执行了then收集的回调函数逻辑>>>>>>>>", res);
        return 2; //链式调用测试
      })
        .then() //值穿透测试
        .then((res) => {
          console.log("返回Promise测试>>>>>>>>>>>>>>", res);
          return new MyPromise((resolve, reject) => {
            resolve(3); // 返回Promise测试
          });
        })
        .then((res) => {
          console.log("reject测试>>>>>>>", res);
          throw new Error("reject测试"); //reject测试
        })
        .then(
          () => {},
          (err) => {
            console.log(err);
          }
        );
    </script>
  </body>
</html>
